In [1]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv

--2025-10-12 08:24:29--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv.3’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.02s   

2025-10-12 08:24:29 (3.10 MB/s) - ‘course_lead_scoring.csv.3’ saved [80876/80876]



In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('course_lead_scoring.csv')

In [4]:
df[:20]

lead_source       industry  number_of_courses_viewed  annual_income  \
0         paid_ads            NaN                         1        79450.0   
1     social_media         retail                         1        46992.0   
2           events     healthcare                         5        78796.0   
3         paid_ads         retail                         2        83843.0   
4         referral      education                         3        85012.0   
5           events  manufacturing                         1        59904.0   
6     social_media     technology                         0        51283.0   
7     social_media            NaN                         5        62975.0   
8         referral     healthcare                         4        38648.0   
9         paid_ads          other                         3        59866.0   
10        paid_ads         retail                         2        79276.0   
11  organic_search        finance                         4        80304.0   
12  organic_search            NaN                         2        55615.0   
13    social_media          other                         3        55438.0   
14        paid_ads     healthcare                         3            NaN   
15        referral     healthcare                         2        56004.0   
16        referral         retail                         0        54612.0   
17        referral          other                         2        92470.0   
18        referral  manufacturing                         2        74380.0   
19        paid_ads            NaN                         2        62809.0   

   employment_status       location  interaction_count  lead_score  converted  
0         unemployed  south_america                  4        0.94          1  
1           employed  south_america                  1        0.80          0  
2         unemployed      australia                  3        0.69          1  
3                NaN      australia                  1        0.87          0  
4      self_employed         europe                  3        0.62          1  
5                NaN         africa                  6        0.83          1  
6                NaN    middle_east                  2        0.57          0  
7            student         europe                  4        0.62          1  
8         unemployed  south_america                  2        0.86          1  
9            student      australia                  3        0.43          1  
10          employed    middle_east                  2        0.92          1  
11     self_employed            NaN                  3        0.97          1  
12     self_employed    middle_east                  6        0.71          1  
13               NaN    middle_east                  1        0.69          0  
14        unemployed    middle_east                  4        0.75          1  
15           student    middle_east                  0        0.64          0  
16     self_employed         europe                  4        0.86          1  
17        unemployed         europe                  4        0.74          1  
18     self_employed            NaN                  5        0.51          1  
19     self_employed         europe                  5        0.33          1

In [5]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [6]:
df.industry.unique()

array([nan, 'retail', 'healthcare', 'education', 'manufacturing',
       'technology', 'other', 'finance'], dtype=object)

In [7]:
df["industry"].value_counts()

industry
retail           203
finance          200
other            198
healthcare       187
education        187
technology       179
manufacturing    174
Name: count, dtype: int64

In [8]:
#Q1 Answer - Most frequent industry is? Answer: Retail
df["industry"].value_counts(dropna=False).sort_values(ascending=False)

industry
retail           203
finance          200
other            198
healthcare       187
education        187
technology       179
manufacturing    174
NaN              134
Name: count, dtype: int64

In [9]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [10]:
df.head(10)

lead_source       industry  number_of_courses_viewed  annual_income  \
0      paid_ads            NaN                         1        79450.0   
1  social_media         retail                         1        46992.0   
2        events     healthcare                         5        78796.0   
3      paid_ads         retail                         2        83843.0   
4      referral      education                         3        85012.0   
5        events  manufacturing                         1        59904.0   
6  social_media     technology                         0        51283.0   
7  social_media            NaN                         5        62975.0   
8      referral     healthcare                         4        38648.0   
9      paid_ads          other                         3        59866.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3               NaN      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1  
5               NaN         africa                  6        0.83          1  
6               NaN    middle_east                  2        0.57          0  
7           student         europe                  4        0.62          1  
8        unemployed  south_america                  2        0.86          1  
9           student      australia                  3        0.43          1

In [11]:
df.lead_source.unique()

array(['paid_ads', 'social_media', 'events', 'referral', 'organic_search',
       nan], dtype=object)

In [12]:
df.industry.unique()

array([nan, 'retail', 'healthcare', 'education', 'manufacturing',
       'technology', 'other', 'finance'], dtype=object)

In [13]:
df.employment_status.unique()

array(['unemployed', 'employed', nan, 'self_employed', 'student'],
      dtype=object)

In [14]:
df.location.unique()

array(['south_america', 'australia', 'europe', 'africa', 'middle_east',
       nan, 'north_america', 'asia'], dtype=object)

In [15]:
df.converted.unique()

array([1, 0])

In [16]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [17]:
df.number_of_courses_viewed.unique()

array([1, 5, 2, 3, 0, 4, 6, 8, 7, 9])

In [18]:
df.number_of_courses_viewed.isnull().sum()

np.int64(0)

In [19]:
df.annual_income.isnull().sum()

np.int64(181)

In [20]:
df.annual_income = df.annual_income.fillna(0.0)

In [21]:
df.annual_income.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
1457    False
1458    False
1459    False
1460    False
1461    False
Name: annual_income, Length: 1462, dtype: bool

In [22]:
df.annual_income.isnull().sum()

np.int64(0)

In [23]:
df.lead_score.isnull().sum()

np.int64(0)

In [24]:
df.lead_source = df.lead_source.fillna("NA")

In [25]:
df.lead_source.isnull().sum()

np.int64(0)

In [26]:
df.industry = df.industry.fillna("NA")

In [27]:
df.industry.isnull().sum()

np.int64(0)

In [28]:
df.employment_status = df.employment_status.fillna("NA")
df.employment_status.isnull().sum()

np.int64(0)

In [29]:
df.location = df.location.fillna("NA")
df.location.isnull().sum()

np.int64(0)

In [30]:
df.head(20)

lead_source       industry  number_of_courses_viewed  annual_income  \
0         paid_ads             NA                         1        79450.0   
1     social_media         retail                         1        46992.0   
2           events     healthcare                         5        78796.0   
3         paid_ads         retail                         2        83843.0   
4         referral      education                         3        85012.0   
5           events  manufacturing                         1        59904.0   
6     social_media     technology                         0        51283.0   
7     social_media             NA                         5        62975.0   
8         referral     healthcare                         4        38648.0   
9         paid_ads          other                         3        59866.0   
10        paid_ads         retail                         2        79276.0   
11  organic_search        finance                         4        80304.0   
12  organic_search             NA                         2        55615.0   
13    social_media          other                         3        55438.0   
14        paid_ads     healthcare                         3            0.0   
15        referral     healthcare                         2        56004.0   
16        referral         retail                         0        54612.0   
17        referral          other                         2        92470.0   
18        referral  manufacturing                         2        74380.0   
19        paid_ads             NA                         2        62809.0   

   employment_status       location  interaction_count  lead_score  converted  
0         unemployed  south_america                  4        0.94          1  
1           employed  south_america                  1        0.80          0  
2         unemployed      australia                  3        0.69          1  
3                 NA      australia                  1        0.87          0  
4      self_employed         europe                  3        0.62          1  
5                 NA         africa                  6        0.83          1  
6                 NA    middle_east                  2        0.57          0  
7            student         europe                  4        0.62          1  
8         unemployed  south_america                  2        0.86          1  
9            student      australia                  3        0.43          1  
10          employed    middle_east                  2        0.92          1  
11     self_employed             NA                  3        0.97          1  
12     self_employed    middle_east                  6        0.71          1  
13                NA    middle_east                  1        0.69          0  
14        unemployed    middle_east                  4        0.75          1  
15           student    middle_east                  0        0.64          0  
16     self_employed         europe                  4        0.86          1  
17        unemployed         europe                  4        0.74          1  
18     self_employed             NA                  5        0.51          1  
19     self_employed         europe                  5        0.33          1

In [31]:
from sklearn.model_selection import train_test_split


In [32]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)


In [33]:
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']
print("interaction_count vs numerical:")
df_full_train[numerical].corrwith(df_full_train.interaction_count).abs().sort_values(ascending=False)

interaction_count vs numerical:


interaction_count           1.000000
annual_income               0.068969
number_of_courses_viewed    0.026417
lead_score                  0.011290
dtype: float64

In [34]:
print("lead_score vs numerical:")
df_full_train[numerical].corrwith(df_full_train.lead_score).abs().sort_values(ascending=False)

lead_score vs numerical:


lead_score                  1.000000
annual_income               0.031716
interaction_count           0.011290
number_of_courses_viewed    0.010711
dtype: float64

In [35]:
#split the data
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
print(len(df_train), len(df_val), len(df_test))

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']



876 293 293


In [36]:
df_full_train = df_full_train.reset_index(drop=True)
df_full_train.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [37]:
#Q3 - Mutual Information 

In [38]:
from sklearn.metrics import mutual_info_score

categorical = ['lead_source', 'employment_status', 'location', 'industry']


In [39]:
round(mutual_info_score(df_full_train.converted, df_full_train.industry),2)

0.01

In [40]:
round(mutual_info_score(df_full_train.converted, df_full_train.location), 2)

0.0

In [41]:
round(mutual_info_score(df_full_train.converted, df_full_train.lead_source), 2)

0.03

In [42]:
round(mutual_info_score(df_full_train.converted, df_full_train.employment_status), 2)

0.01

In [43]:
#Q4 - Logistic regression and accuracy

In [44]:
#One Hot Encoding using DictVectorizer in sklearn

from sklearn.feature_extraction import DictVectorizer


dv = DictVectorizer(sparse=False)
train_dict = df_train[categorical + numerical].to_dict(orient='records')
print(train_dict[0])
X_train = dv.fit_transform(train_dict)
X_train



{'lead_source': 'paid_ads', 'employment_status': 'student', 'location': 'middle_east', 'industry': 'retail', 'number_of_courses_viewed': 0, 'annual_income': 58472.0, 'interaction_count': 5, 'lead_score': 0.03}


array([[5.8472e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [7.1738e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [8.1973e+04, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [8.9042e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.0259e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+00]], shape=(876, 31))

In [45]:
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=other',
       'industry=retail', 'industry=technology', 'interaction_count',
       'lead_score', 'lead_source=NA', 'lead_source=events',
       'lead_source=organic_search', 'lead_source=paid_ads',
       'lead_source=referral', 'lead_source=social_media', 'location=NA',
       'location=africa', 'location=asia', 'location=australia',
       'location=europe', 'location=middle_east',
       'location=north_america', 'location=south_america',
       'number_of_courses_viewed'], dtype=object)

In [46]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [47]:
# Logistic Regression using sklearn

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [50]:
model.coef_.shape

(1, 31)

In [51]:
# Weights w
model.coef_[0].round(3)

array([-0.   , -0.015,  0.034,  0.003,  0.012, -0.103, -0.025,  0.049,
       -0.02 , -0.013, -0.003, -0.009, -0.032, -0.016,  0.311,  0.051,
        0.02 , -0.012, -0.012, -0.115,  0.08 , -0.03 ,  0.004, -0.011,
       -0.011, -0.006,  0.008,  0.006, -0.033, -0.025,  0.454])

In [52]:
#b - bias or intercept
model.intercept_


array([-0.06914728])

In [53]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [54]:
categorical

['lead_source', 'employment_status', 'location', 'industry']

In [55]:
numerical

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [56]:
y_pred = model.predict_proba(X_val)[:,1] # column 0 is probability of index 0, column 1 is probability of 1, we just need index 1

In [57]:
y_pred

array([0.61192163, 0.79982617, 0.53021343, 0.47131479, 0.57066131,
       0.44227168, 0.87127669, 0.84883115, 0.83290037, 0.61497801,
       0.54968026, 0.78153088, 0.69039785, 0.77017122, 0.5265944 ,
       0.91706425, 0.53170634, 0.42123048, 0.30146455, 0.84881583,
       0.79488653, 0.73670374, 0.4452721 , 0.64838383, 0.4176882 ,
       0.75393418, 0.90166116, 0.33903048, 0.43181431, 0.9680681 ,
       0.92018714, 0.37487988, 0.65230099, 0.90650057, 0.75164116,
       0.64202121, 0.82250075, 0.83375553, 0.659116  , 0.30978853,
       0.78942264, 0.35546365, 0.96517758, 0.63389304, 0.51274195,
       0.53230533, 0.82287785, 0.744074  , 0.73452313, 0.68955217,
       0.46964443, 0.84539252, 0.55635243, 0.92637871, 0.65258021,
       0.61526273, 0.63816995, 0.28304018, 0.48049824, 0.57890618,
       0.35497342, 0.62175051, 0.38960777, 0.61156056, 0.85304278,
       0.75430136, 0.89185954, 0.71946458, 0.95387623, 0.89209517,
       0.75277087, 0.33850139, 0.61376593, 0.51622275, 0.64088

In [58]:
will_convert = (y_pred >= 0.5)

In [59]:
will_convert

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,

In [60]:
accuracy_score = (y_val == will_convert).mean()
accuracy_score

np.float64(0.6996587030716723)

In [61]:
round(accuracy_score, 2)

np.float64(0.7)

In [63]:
# from sklearn.feature_extraction import DictVectorizer
# from sklearn.linear_model import LogisticRegression

# dv = DictVectorizer(sparse=False)
# train_dict = df_train[categorical + numerical].to_dict(orient='records')
# print(train_dict[0])
# X_train = dv.fit_transform(train_dict)
# print(X_train)
# print(dv.get_feature_names_out())

# val_dict = df_val[categorical + numerical].to_dict(orient='records')
# X_val = dv.transform(val_dict)

# model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# model.fit(X_train, y_train)
# print(model.coef_[0].round(3))
# print(model.intercept_)

# y_pred = model.predict_proba(X_val)[:,1]
# print(y_pred)

# accuracy_score = (y_val == will_convert).mean()
# accuracy_score

In [112]:
#Q5: Least Useful Column

In [113]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [114]:
def train_and_evaluate(df_train1, df_val1, y_train1, y_val1, columns):
    """
    Trains a Logistic Regression model using the given columns and returns the accuracy score.
    """
    # Vectorize
    dv = DictVectorizer(sparse=False)
    train_dict = df_train1[columns].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    
    val_dict = df_val1[columns].to_dict(orient='records')
    X_val = dv.transform(val_dict)
    
    # Train model
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train1)
    
    # Predict
    y_pred = model.predict_proba(X_val)[:, 1]
    y_pred_labels = (y_pred >= 0.5).astype(int)
    
    # Compute accuracy
    acc = accuracy_score(y_val1, y_pred_labels)
    
    return acc

In [115]:
def feature_exclusion_experiment(df_train1, df_val1, y_train1, y_val1, all_columns):
    """
    Runs training with all columns and then with each column removed one at a time.
    Prints the resulting accuracy for each configuration.
    """
    # Run with all columns
    acc_all = train_and_evaluate(df_train1, df_val1, y_train1, y_val1, all_columns)
    print(f"all columns: {acc_all:.4f}")
    
    # Run with one column removed each time
    least_useful_col = ''
    least_useful_acc = 1
    least_useful_acc_delta = 1

    for col in all_columns:
        cols_subset = [c for c in all_columns if c != col]
        acc = train_and_evaluate(df_train1, df_val1, y_train1, y_val1, cols_subset)
        print(f"\nwithout '{col}': {acc:.4f}")
        cur_least_useful_acc_delta = abs(acc_all - acc)
        print("current usefulness:", cur_least_useful_acc_delta)
        if cur_least_useful_acc_delta < least_useful_acc_delta:
            least_useful_acc = acc
            least_useful_col = col
            least_useful_acc_delta = cur_least_useful_acc_delta

    print("\n\n")
    print("all_column_acc:", acc_all)
    print("least_useful_col:", least_useful_col)
    print("least_useful_acc:", least_useful_acc)
    print("Delta of accuracy with and without this column:", least_useful_acc_delta)


In [116]:
len(df.columns)

9

In [117]:
numerical

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [118]:
categorical

['lead_source', 'employment_status', 'location', 'industry']

In [119]:
input_columns = categorical + numerical
input_columns

['lead_source',
 'employment_status',
 'location',
 'industry',
 'number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [120]:
feature_exclusion_experiment(df_train, df_val, y_train, y_val, input_columns)

all columns: 0.6997

without 'lead_source': 0.7031
current usefulness: 0.0034129692832765013

without 'employment_status': 0.6962
current usefulness: 0.0034129692832763903

without 'location': 0.7099
current usefulness: 0.010238907849829393

without 'industry': 0.6997
current usefulness: 0.0

without 'number_of_courses_viewed': 0.5563
current usefulness: 0.14334470989761094

without 'annual_income': 0.8532
current usefulness: 0.15358361774744034

without 'interaction_count': 0.5563
current usefulness: 0.14334470989761094

without 'lead_score': 0.7065
current usefulness: 0.0068259385665528916



all_column_acc: 0.6996587030716723
least_useful_col: industry
least_useful_acc: 0.6996587030716723
Delta of accuracy with and without this column: 0.0


In [ ]:
#Q6: Accuracy based on different regularization values for C

In [ ]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

dv = DictVectorizer(sparse=False)
train_dict = df_train[categorical + numerical].to_dict(orient='records')
print(train_dict[0])
X_train = dv.fit_transform(train_dict)
print(X_train)
print(dv.get_feature_names_out())

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)
print(model.coef_[0].round(3))
print(model.intercept_)

y_pred = model.predict_proba(X_val)[:,1]
print(y_pred)

accuracy_score = (y_val == will_convert).mean()
accuracy_score

In [129]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
import numpy as np

def accuracy_with_regularization(df_train1, df_val1, columns, y_train1, y_val1, C=1.0):
    """
    Train a Logistic Regression model with specified regularization (C)
    and return accuracy score on validation data.
    
    Parameters:
        df_train: pandas DataFrame - training data
        df_val: pandas DataFrame - validation data
        categorical: list[str] - categorical column names
        numerical: list[str] - numerical column names
        y_train: Series or array - training labels
        y_val: Series or array - validation labels
        C: float - inverse of regularization strength (default=1.0)
        
    Returns:
        float - validation accuracy
    """
    
    # Vectorize training data
    dv = DictVectorizer(sparse=False)
    train_dict = df_train1[columns].to_dict(orient='records')
    # print("Sample training record:\n", train_dict[0])
    
    X_train = dv.fit_transform(train_dict)
    # print("Feature names:\n", dv.get_feature_names_out())

    # Vectorize validation data
    val_dict = df_val1[columns].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    # Train logistic regression model
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train1)
    
    # print("Model coefficients:\n", model.coef_[0].round(3))
    # print("Intercept:", model.intercept_)
    
    # Predict probabilities for validation set
    y_pred = model.predict_proba(X_val)[:, 1]
    # print("Predicted probabilities:\n", np.round(y_pred[:10], 3))  # show first 10
    
    # Convert probabilities to binary predictions (using 0.5 threshold)
    will_convert = (y_pred >= 0.5)
    
    # Calculate accuracy
    accuracy_score = round((y_val1 == will_convert).mean(), 3)
    
    
    print(f"Validation Accuracy (C={C}): {accuracy_score:.4f}")
    return accuracy_score


In [130]:
columns = numerical + categorical
columns

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'lead_source',
 'employment_status',
 'location',
 'industry']

In [131]:
for c in [0.01, 0.1, 1, 10, 100]:
    accuracy_with_regularization(df_train, df_val, columns, y_train, y_val, C=c)

Validation Accuracy (C=0.01): 0.7000
Validation Accuracy (C=0.1): 0.7000
Validation Accuracy (C=1): 0.7000
Validation Accuracy (C=10): 0.7000
Validation Accuracy (C=100): 0.7000
